### ISSUE TITLE
Use tileserver-gl to serve raster tiles with the same mapbox-GL json style format

### ISSUE THREAD

**Issue by amatissart** [QwantResearch/kartotherian_docker#10]
[tileserver-gl](https://github.com/klokantech/tileserver-gl) achieves exactly that (based on node-js mapbox-gl-native)

tileserver-gl config : 
```
{
  "styles":{
    "<myStyleName>": {
       "style": "path/to/mapbox-gl-style.json"
    }
  }
}
```
kartotherian source : 
```
osm-intl: 
  uri: http://localhost:8080/styles/<myStyleName>/{z}/{x}/{y}.png
  public: true
  formats: [png]
  scales: [1.3, 1.5, 2, 2.6, 3]
  static: true
  maxheight: 2048
  maxwidth: 2048
```

**BUT**
Some parameters are not applied in the upstream "uri" (e.g scale "@2x" does not work)

**_Solution 1_** : Patch tilelive-http to apply scale from `callback.scale`.
cf https://github.com/mojodna/tilelive-http/blob/040d70020e561d19e1ae19187beb295d019eb730/index.js#L122

**_Solution 2_** : Create a proper source protocol (alternative to tilelive-vector) to serve raster tiles using tileserver-gl.
